#ifndef FILESYSTEMWATCHERLIB_GLOBAL_H
#define FILESYSTEMWATCHERLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FILESYSTEMWATCHERLIB_LIBRARY)
#  define FILESYSTEMWATCHERLIB_EXPORT Q_DECL_EXPORT
#else
#  define FILESYSTEMWATCHERLIB_EXPORT Q_DECL_IMPORT
#endif

#endif // FILESYSTEMWATCHERLIB_GLOBAL_H
