#ifndef IMAGEDOWNLOADER_GLOBAL_H
#define IMAGEDOWNLOADER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(IMAGEDOWNLOADER_LIBRARY)
#  define IMAGEDOWNLOADER_EXPORT Q_DECL_EXPORT
#else
#  define IMAGEDOWNLOADER_EXPORT Q_DECL_IMPORT
#endif

#endif // IMAGEDOWNLOADER_GLOBAL_H
